
- name: Give the tomcat group ownership
  file:
    path: /opt/tomcat
    group: tomcat
    recurse: yes
    state: directory

- name: give tomcat read access to the conf file
  file:
    path: /opt/tomcat/conf
    state: directory
    mode: g+r
    recurse: yes

- name: give tomcat execute access to the conf file
  file:
    path: /opt/tomcat/conf
    state: directory
    mode: g+x

- name: make the tomcat user the owner of the webapps
  file:
    path: /opt/tomcat/webapps/
    state: directory
    recurse: yes
    owner: tomcat

- name: make the tomcat user the owner of the work
  file:
    path: /opt/tomcat/work/
    state: directory
    recurse: yes
    owner: tomcat

- name: make the tomcat user the owner of the logs
  file:
    path: /opt/tomcat/logs/
    state: directory
    recurse: yes
    owner: tomcat

- name: make the tomcat user the owner of the temp
  file:
    path: /opt/tomcat/temp/
    state: directory
    recurse: yes
    owner: tomcat


